services:
  spark-master:
    image: apache/spark:3.4.2
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8090:8080"   # Spark Master Web UI
      - "7077:7077"   # Spark Master RPC
    command: ["/opt/spark/sbin/start-master.sh"]
    environment:
      - SPARK_NO_DAEMONIZE=true
      - IVY_HOME=/tmp/.ivy2
    volumes:
      - spark-master-data:/opt/spark/data
      - ./src:/opt/spark/work-dir/src:ro
    networks:
      - pipeline-network

  spark-worker-1:
    image: apache/spark:3.4.2
    container_name: spark-worker-1
    hostname: spark-worker-1
    ports:
      - "8081:8081"   # Spark Worker Web UI
    command: ["/opt/spark/sbin/start-worker.sh", "spark://spark-master:7077"]
    environment:
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - spark-worker-1-data:/opt/spark/data
    networks:
      - pipeline-network
    depends_on:
      - spark-master

  spark-worker-2:
    image: apache/spark:3.4.2
    container_name: spark-worker-2
    hostname: spark-worker-2
    ports:
      - "8082:8081"   # Spark Worker Web UI
    command: ["/opt/spark/sbin/start-worker.sh", "spark://spark-master:7077"]
    environment:
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - spark-worker-2-data:/opt/spark/data
    networks:
      - pipeline-network
    depends_on:
      - spark-master

volumes:
  spark-master-data:
  spark-worker-1-data:
  spark-worker-2-data:

networks:
  pipeline-network:
    name: pipeline-network
    external: true
