services:
  hdfs-namenode:
    platform: linux/amd64
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-namenode
    hostname: hdfs-namenode
    ports:
      - "9870:9870"   # NameNode Web UI
      - "9000:9000"   # NameNode RPC
      - "8020:8020"   # NameNode service RPC
    volumes:
      - hdfs-namenode-data:/hadoop/dfs/name
      - ./data:/data
    env_file:
      - .env
    environment:
      - CLUSTER_NAME=flight-analytics
      - HDFS_CONF_dfs_replication=3
    networks:
      - pipeline-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870"]
      interval: 30s
      timeout: 10s
      retries: 10

  hdfs-datanode-1:
    platform: linux/amd64 # This is added to ensure compatibility with Apple Silicon Macs
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-datanode-1
    hostname: hdfs-datanode-1
    ports:
      - "9864:9864"   # DataNode Web UI
    volumes:
      - hdfs-datanode-1-data:/hadoop/dfs/data
    env_file:
      - .env
    environment:
      - SERVICE_PRECONDITION=hdfs-namenode:9870
      - HDFS_CONF_dfs_replication=3
    networks:
      - pipeline-network
    depends_on:
      hdfs-namenode:
        condition: service_healthy

  hdfs-datanode-2:
    platform: linux/amd64
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-datanode-2
    hostname: hdfs-datanode-2
    ports:
      - "9865:9864"   # DataNode Web UI
    volumes:
      - hdfs-datanode-2-data:/hadoop/dfs/data
    env_file:
      - .env
    environment:
      - SERVICE_PRECONDITION=hdfs-namenode:9870
      - HDFS_CONF_dfs_replication=3
    networks:
      - pipeline-network
    depends_on:
      hdfs-namenode:
        condition: service_healthy

  hdfs-datanode-3:
    platform: linux/amd64
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-datanode-3
    hostname: hdfs-datanode-3
    ports:
      - "9866:9864"   # DataNode Web UI
    volumes:
      - hdfs-datanode-3-data:/hadoop/dfs/data
    env_file:
      - .env
    environment:
      - SERVICE_PRECONDITION=hdfs-namenode:9870
      - HDFS_CONF_dfs_replication=3
    networks:
      - pipeline-network
    depends_on:
      hdfs-namenode:
        condition: service_healthy

volumes:
  hdfs-namenode-data:
  hdfs-datanode-1-data:
  hdfs-datanode-2-data:
  hdfs-datanode-3-data:

networks:
  pipeline-network:
    name: pipeline-network
    external: true
